In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from bs4 import BeautifulSoup as bs

In [2]:
r = requests.get('https://nigeriapropertycentre.com/for-rent')
soup = bs(r.content)

In [12]:
# def get_url(url):
#     page = requests.get(url)
#     houses = bs(page.content)
#     return houses

def get_details(url):
    property_details = {}
#     get_url(url)
    page = requests.get(url)
    house = bs(page.content)
    table = house.find('table')
    content = [item.get_text().split(':') for item in table.find_all('td')]
    property_details['Period'] = house.find('span', class_='period').get_text().replace('\xa0', "")
    property_details['Price'] = house.find_all('span', class_='price')[1].get_text().replace('\xa0', "")
    property_details['Type'] = house.find('h4', class_='content-title').get_text().replace('\xa0', "")
    property_details['Location']= house.find('p').get_text().replace('\xa0', "")
    for text in content:
        property_details[text[0]] = text[-1].replace('[', "").replace(']', "").replace('\xa0', "")
    return property_details

def get_properties(url, page_num):
    housing_dataset_list = []
    page = requests.get(url)
    house = bs(page.content)
    num_pages = int(house.find('ul', class_='pagination').find_all('li')[-2].get_text())
    for page in range(1001,1045):
        print(page)
        properties = house.find_all('div', class_='property-list')
        rel_url = [item.find('div', class_='wp-block-title').a.get('href') for item in properties]
        for link in rel_url:
            housing_dataset_list.append(get_details('https://nigeriapropertycentre.com'+link))
        page_num=+1
        url = f'https://nigeriapropertycentre.com/for-rent?page={page_num}'
        page = requests.get(url)
        house = bs(page.content)  
    housing_dataset = pd.DataFrame(housing_dataset_list)
    return housing_dataset

In [13]:
properties = get_properties('https://nigeriapropertycentre.com/for-rent', 1)
df=pd.DataFrame(properties).to_csv(r'C:/Users/lukman/Documents/Machine learning/Data/housing_data9.csv')
df

1001
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044

In [24]:
df=pd.DataFrame(properties)
df

,Period,Price,Type,Location,Property Ref,Added On,Last Updated,Market Status,Bedrooms,Bathrooms,Toilets,,Parking Spaces,Servicing,Service Charge,Total Area,Covered Area,Furnishing
0,per annum,"8,000,000",Terraced Duplex,"Oniru, Victoria Island (VI), Lagos",1243809,02 Mar 2022,11 Apr 2022,Available,5,5,6,,NaN,NaN,NaN,NaN,NaN,NaN
1,per annum,"3,500,000",Terraced Duplex,"Ikota Primary Sch, Lekki, Lagos",1310063,05 May 2022,05 May 2022,Available,4,5,5,,3,Serviced,"₦40,000 per month",NaN,NaN,NaN
2,per annum,"5,000,000",Terraced Duplex,"Asokoro District, Abuja",1309707,05 May 2022,05 May 2022,Available,4,5,5,,NaN,Serviced,"₦500,000",NaN,NaN,NaN
3,per square meter / per annum,"40,000",Office Space,"Herbert Macaulay Way, Central Business Distri...",1235981,22 Feb 2022,26 Apr 2022,Available,NaN,2,2,NaN,1,Serviced,"₦11,000 per annum",600 sqm,500 sqm,NaN
4,per annum,"5,000,000",Terraced Duplex,"Gated And Secured Area, Jakande, Lekki, Lagos",1310218,05 May 2022,05 May 2022,Available,4,4,5,,3,NaN,NaN,300 sqm,200 sqm,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1045,per annum,"13,000,000",Terraced Duplex,"Ikoyi, Old Ikoyi, Ikoyi, Lagos",1238629,24 Feb 2022,05 May 2022,Available,4,3,4,,2,Serviced,"₦4,500,000 per annum",NaN,NaN,NaN
1046,per annum,"1,500,000",Flat / Apartment,"Off Bus Stop Surulere Lagos, Kilo, Surulere, ...",1310249,05 May 2022,05 May 2022,Available,3,3,4,NaN,2,NaN,NaN,NaN,NaN,NaN
1047,per annum,"5,500,000",Terraced Duplex,"Osapa, Lekki, Lagos",1310248,05 May 2022,05 May 2022,Available,4,4,5,,NaN,Serviced,"₦60,000 per month",NaN,NaN,NaN
1048,per annum,"4,500,000",Flat / Apartment,"Elf, Whitesand School Road, Lekki, Lagos",1310243,05 May 2022,05 May 2022,Available,2,2,3,,2,Serviced,"₦1,800,000 per annum",NaN,NaN,NaN
1049,per annum,"20,000,000",Terraced Duplex,"Banana Island, Ikoyi, Lagos",1240624,26 Feb 2022,05 May 2022,Available,4,4,5,,2,Serviced,NaN,NaN,NaN,NaN

In [27]:
check = get_details('https://nigeriapropertycentre.com/for-rent/flats-apartments/self-contained/lagos/lekki/lekki-phase-1/1300250-extremely-spacious-room-self-contained-big-enough-for-room-parlor')

In [13]:
check

{'Period': ' per annum',
 'Price': '2,400,000',
 'Type': ' Self Contain (Single Rooms)',
 'Location': ' Moore Olatunji Street, Off Pinnacle Fuel Statio, Lekki Phase 1, Lekki, Lagos',
 'Property Ref': ' 1300250',
 'Added On': ' 25 Apr 2022',
 'Last Updated': ' 02 May 2022',
 'Market Status': ' Available',
 'Bathrooms': ' 1',
 'Toilets': ' 1',
 'Servicing': ' Serviced',
 'Service Charge': ' ₦7,300 per annum'}